name: ihc_p3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  external_app_launcher: ^4.0.3
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_background_service: ^5.1.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^2.5.2
  flutter_tts: ^4.2.3
  http: ^1.4.0
  shake: ^3.0.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
